version: '3.3'
services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - database:/var/lib/postgesql/data
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: kvot32/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: kvot32/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  database:
  static_value:
  media_value: